stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cloudnautique/pipeline:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/singleshot.yml
  when:
    branch:
      include:
      - master
timeout: 60
branch: {}
